Implement nyapic
item4/yui pull request #77
Opened 2017-11-15 16:17 UTC by Kjwon15

Nyanyanyanyanyanyanya!

2017-11-16 02:05 UTC, item4 commented
API 발급받을 필요 없는 http://thecatapi.com/ 를 사용합시다

2017-11-16 02:19 UTC, item4 requested changes
요약

1. http://thecatapi.com/
2. nya -> cat
3. decorator -> util로 / MIT전환 동의 필요

2017-11-16 02:19 UTC, item4 commented on yui/handlers/nya.py
> +def static_vars(**kwargs):
이 메소드는 yui.util로 옮겼으면 좋겠어요. 근데 그러면 이 함수는 MIT로 전환됩니다

2017-11-16 02:19 UTC, item4 commented on yui/handlers/nya.py
> +@box.command('nya')
nya는 nyaa랑 너무 비슷한 것 같아요. cat 정도로 하는게 나을 것 같아요

2017-11-16 02:20 UTC, item4 commented on yui/handlers/nya.py
> +@box.command('nya')
대신 alias로 '냥' 같은걸 추가하죠

2017-11-16 06:17 UTC, item4 commented
#78 문제로 master 브랜치가 수정되었으니 rebase도 해주셔야할것같은

2017-11-16 06:23 UTC, Kjwon15 commented
1.  thecatapi는 퀄리티가 너무 낮아서 giphy를 쓴 거였습니다. 근데 지금 보니 괜찮네요. 제가 초창기 때 봐서 그런 듯.
추가로 giphy는 API 키를 발급 받으라고는 하는데 발급 안 받아도 `dc6zaTOxFJmzC`를 키로 쓰라고 나와 있고 다들 그걸 씁니다. 
2-3번은 금방 수정할게요

2017-11-16 06:42 UTC, item4 requested changes

2017-11-16 06:42 UTC, item4 commented on yui/handlers/nya.py
>  @static_vars({'last_call': None})
이거 에러날 것 같은데요. `static_vars`에선 `**kwargs`로 받는데 여긴 그냥 `dict`라서...

`@static_vars(**{'last_call': None})` 내지는 `@static_vars(last_call=None)` 이 되어야 맞을 것 같습니다.

2017-11-16 06:53 UTC, Kjwon15 commented
아아아아 제가 멍청했네요

On Thu, 16 Nov 2017, 15:42 item4, <notifications@github.com> wrote:

> *@item4* requested changes on this pull request.
> ------------------------------
>
> In yui/handlers/nya.py
> <https://github.com/item4/yui/pull/77#discussion_r151331116>:
>
> >
>
> -def static_vars(**kwargs):
> -    def decorator(func):
> -        for key, val in kwargs.items():
> -            setattr(func, key, val)
> -
> -        return func
> -    return decorator
> -
> -
> -@box.command('nya')
> +@box.command('cat')
>  @static_vars({'last_call': None})
>
> 이거 에러날 것 같은데요. static_vars에선 **kwargs로 받는데 여긴 그냥 dict라서...
>
> @static_vars(**{'last_call': None}) 내지는 @static_vars(last_call=None) 이
> 되어야 맞을 것 같습니다.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/item4/yui/pull/77#pullrequestreview-77020921>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AE0Fg5D9bVtw4kWhD3pcO2DLPtywl9oLks5s29k-gaJpZM4QfLto>
> .
>

2017-11-16 07:45 UTC, item4 commented on yui/handlers/cat.py
> +from xml.etree import ElementTree
의존성에 lxml이 이미 있습니다. lxml을 쓰는게 더 빠르지 않을까요?

2017-11-16 07:45 UTC, item4 commented on yui/handlers/cat.py
>  async def nya(bot, event: Message, sess):
여기 함수명도 cat으로 바꾸는게 통일성이 있을 것 같아요

2017-11-16 07:58 UTC, item4 requested changes

2017-11-16 07:58 UTC, item4 commented on yui/handlers/cat.py
> +from xml.etree import ElementTree
리뷰가 날아가버려서 다시 작성. 이미 lxml이 설치되어있는데 lxml을 사용하는게 어떨까요

2017-11-16 07:58 UTC, item4 commented on yui/handlers/cat.py
> +async def nya(bot, event: Message, sess):
함수명을 `cat`으로 통일했으면 합니다

2017-11-16 07:58 UTC, item4 commented
travis 코드가 계속 바뀌어서 rebase 다시 해주셔야 할듯한 ㅠㅠ

2017-11-17 09:32 UTC, item4 requested changes

2017-11-17 09:32 UTC, item4 commented on yui/handlers/cat.py
> +async def cat(bot, event: Message, sess):
유이의 help 명령어를 위해서는 명령어의 도움말을 작성해야해요. 안 그러면 `None`으로 나와버려요.
가장 쉬운 도움말 작성법은 docstring을 작성하는거에요. 다른 명령어 참조해서 간단히 적어주세요

2017-11-18 08:29 UTC, item4 approved these changes

2017-11-18 08:33 UTC, item4 commented
@Kjwon15 파일명때문에 빌드가 깨져요. 그거만 고치면 될 것 같은...

2017-11-18 11:11 UTC, item4 requested changes

2017-11-18 11:11 UTC, item4 commented on yui/handlers/__init__.py
> +from .nya import *  # type: ignore
nya -> cat

2017-11-18 15:00 UTC, item4 approved these changes

2017-11-18 15:00 UTC, merged