Shut up the dog when holidays
item4/yui pull request #96
Opened 2017-12-31 16:49 UTC by Kjwon15

![](https://i.ytimg.com/vi/E5DefZI_tTE/maxresdefault.jpg)

2018-01-01 06:17 UTC, item4 requested changes
얍

2018-01-01 06:17 UTC, item4 commented on yui/handlers/loading.py
> +import json
ujson을 사용해주세요

2018-01-01 06:17 UTC, item4 commented on yui/handlers/loading.py
> +            '!' * random.randint(3, 10),
이렇게 하면 `월월월월` 따로 `!!!!` 따로 별도의 메시지로 나옵니다. `월월월월!!!!` 같이 나오게 하려면 둘이 붙여야 할 것 같아요

2018-01-01 06:17 UTC, item4 commented on yui/handlers/loading.py
> +async def get_holiday_name(dt: datetime):
`datetime` -> `datetime.datetime`

2018-01-01 06:17 UTC, item4 commented on yui/handlers/loading.py
> +    if (holidays):
`()`는 필요 없는것 같아요

2018-01-01 09:57 UTC, Kjwon15 commented on yui/handlers/loading.py
> +            '!' * random.randint(3, 10),
의도한 겁니다. 짖다가 ??!!?! 하고 깨닫는 거죠.

2018-01-01 10:33 UTC, item4 requested changes

2018-01-01 10:33 UTC, item4 commented on yui/handlers/loading.py
> +            '!' * random.randint(3, 10),
그럼 `!` 만 나오지 말고 `?`도 나오고 앞에 `.`도 붙여서 `....!!!?!?!?!?!` 이런 형태로 만들어서 당황스러움을 극대화 시켜봅시다

2018-01-01 10:33 UTC, item4 commented on yui/handlers/loading.py
> +import ujson
아마 100% 확률로 flake8-import-order에서 죽을겁니다

2018-01-03 07:08 UTC, item4 approved these changes

2018-01-03 07:09 UTC, merged